---
title: "final-project"
author: "benton anderson"
date: "4/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)
library(magrittr)
library(tidyverse)
library(data.table)
```



```{r}
df <- read.csv("./sample.csv", stringsAsFactors = FALSE)
df$date <- as.Date(df$datetime)

justone <- df[df$symbol == 'PRTA',]
justone <- justone[1:200,]

for (i in 30:nrow(justone)){
  
  target <- justone$date[i] - as.difftime(31, unit="days")
  
  #found <- justone[justone$datetime > target, 'datetime']
  
  print(justone$date[i])
  print(target)
  print("\n")
}

justone
```

```{r}
sample <- read.csv("./sample.csv", stringsAsFactors = FALSE)
sample$date <- as.Date(sample$datetime)
sample$symbol <- as.factor(sample$symbol)

justone <- sample[sample$symbol == 'PRTA',]
justone <- justone[1:200,]



add_return_pct <- function(x, y){
  df <- x
  df$close_30_ago = NA
  df$date_30_ago = NA
  
  date_offset <- 22
  for (i in (date_offset+1):nrow(df)){
    # TODO - do fancy date parsing for more exact offsets
    df$date_30_ago[i] <- as.character(df$date[i - date_offset])
    df$close_30_ago[i] <- df$close[i - date_offset]
  }
  
  df$last_30_return <- df$close / df$close_30_ago - 1
  df$annualized_last_30_return = (df$last_30_return + 1) ^ (365/30) - 1
  df
}

by_symbol <- sample %>% group_by(symbol) %>% group_map(add_return_pct, keep = TRUE)
by_symbol
```

```{r}
# Create data table with 30 day stock returns by ticker name (includes date)

varname <- as.character(by_symbol[[1]]$symbol[1])
stock_returns <- data.table(date=by_symbol[[1]]$date, return=by_symbol[[1]]$last_30_return)
setnames(stock_returns, "return",paste(varname))

for (i in 2:length(by_symbol)){
  varname <- as.character(by_symbol[[i]]$symbol[1])
  dt <- data.table(date=by_symbol[[i]]$date, return= by_symbol[[i]]$last_30_return)
  setnames(dt, "return",paste(varname))
  
stock_returns <- left_join(stock_returns,dt, by="date")
}





View(stock_returns)
```

```{r}
with_returns <- rbindlist(by_symbol)
View(with_returns)
```

```{r}
#colreturns <- 
```

```{r}

symbol_list <- levels(as.factor(sample$symbol))

symbol_stats <- data.frame(symbol = symbol_list)

portfolio <- with_returns %>% 
  group_by(symbol) %>% 
  summarise(mean=mean(last_30_return, na.rm=TRUE), sd=sd(last_30_return, na.rm=TRUE))

portfolio$weight <- 1/nrow(portfolio)
portfolio$return <- portfolio$mean * portfolio$weight


total_return <- sum(portfolio$return)
(total_return + 1) ** 12
portfolio
```


```{r}
model_string <- textConnection("model{
  # Likelihood
  for(i in 1:n){
    Y[i] ~ dnorm(mu[i], prec[i])
  }
  
  # Prior
  for (i in 1:n){
    mu[i] ~ dnorm(mean[i], taumu)
    sd[i] ~ dnorm(obsd[i], tauv)
    prec[i] <- 1/sd[i]
  }
  
  taumu ~ dgamma(0.1, 0.1)
  tauv ~ dgamma(0.1, 0.1)
  
}")
```


```{r}
timestamp()
data <- list(
  obsd=portfolio$sd,
  Y=portfolio$mean,
  mean=portfolio$mean,
  n=nrow(portfolio)
)

model <- jags.model(model_string,data=data,n.chains=2)
```


```{r}
timestamp()
update(model, 20000)
timestamp()
params = c('mu')
samples <- coda.samples(model, variable.names=params, thin=10, n.iter=50000)
timestamp()
```

```{r}
plot(model2_samples)
```

