---
title: "Bayesian Portfolio"
author: "Chris Hooks"
date: "4/19/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rjags)
library(data.table)
library(tidyverse)
library(LaplacesDemon)
library(mvtnorm)
```

```{r}
df <- read.csv("./sample_6.csv", stringsAsFactors = FALSE)
df$date <- as.Date(df$datetime)
df$symbol <- as.factor(df$symbol)


by_symbol <- df %>% group_by(symbol) %>% group_map(function(x, y){x}, keep = TRUE)
```


```{r}

# Daily returns
N <- nrow(by_symbol[[1]])
C <- length(by_symbol)

daily_close <- matrix(NA, N,C+1)
colnames(daily_close) <- c("date",levels(as.factor(df$symbol)))
daily_close[,"date"] <- by_symbol[[1]]$date
for (i in 1:C){
  daily_close[,(i+1)] <- by_symbol[[i]]$close
}

daily_return <- matrix(NA, N, C+1)
colnames(daily_return) <- colnames(daily_close)
daily_return[,1] <- daily_close[,1]

for (j in 2:(C+1)){
  for (i in 2:N){
    daily_return[i,j] <- 100*(daily_close[i,j] / daily_close[i-1,j]-1)
  }
}

daily_return <- daily_return[2:N,2:(C+1)]
```

```{r}
set.seed(183)

S <- 10000
port_samples <- matrix(NA,S,3)

T <- nrow(daily_return)

# Initial Values
mu1 <- colMeans(daily_return)
cov1 <- cov(daily_return)
```

Model 1
```{r}
# Portfolio returns

model_1_string <- textConnection("model{

# Priors

for (i in 1:Nstocks){
  mu[i] ~ dnorm(0,0.1)
}

Omega[1:Nstocks,1:Nstocks] ~ dwish(scale[,],df)

# Likelihood

for (i in 2:T){
  stock_returns[i,1:Nstocks] ~ dmnorm(mu, Omega[,])
}
}")

Nstocks <- ncol(daily_return)
scale <- diag(Nstocks)

data <- list(stock_returns=daily_return, scale=scale, df=N-1, T=T, Nstocks=Nstocks)
init <- list(mu=mu1) # something like? Omega=solve(cov1)) https://sourceforge.net/p/mcmc-jags/discussion/610037/thread/eab372de/
params <- c("Omega","mu")
model_1 <- jags.model(model_1_string, data=data, inits=init, n.chains = 2, quiet=TRUE)
```

```{r}
update(model_1, 15000)
samp_1 <- coda.samples(model_1, variable.names = params, n.iter=10000)
```

```{r}
plot(samp_1)
```
```{r}
samples <- cbind(samp_1[[1]])
Omega_samples <- samples[,1:Nstocks^2]
mu_start <- Nstocks^2 + 1
mu_end <- mu_start + Nstocks - 1
mu_samples <- samples[,mu_start:mu_end]
```


```{r}

sample_index <- sample(1:nrow(Omega_samples), 1)
covmat <- matrix(Omega_samples[sample_index,], nrow=Nstocks, ncol=Nstocks)

mu <- mu_samples[sample_index]

draw <- rmvnorm(n=1, mean=mu1, sigma=covmat)

w <- runif(Nstocks)
w <- w/sum(w)


sharpe <- function(w){
  E <- draw %*% w
  port_var <- t(w) %*% covmat %*% w
  E/sqrt(port_var)
} 

optimization <- optim(
  w, # initial guess
  sharpe, # fn to optimize
  method = c("L-BFGS-B"), # only l-bfgs-b and brent support bounding
  control=list(
    maxit=10000, # default iters isn't enough to converge
    fnscale=-1 # We want to maximize, not minimize
  ),
  lower=0 # lower bound for each var
)

optimal <- optimization$par

normalized_optimal <- optimal/sum(optimal)

normalized_optimal
```

